# -*- coding: utf-8 -*-
"""App_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UzBH_J4rfrzNVCxLdqj1njQnUV3eK8rn
"""

from Train_1 import * #Importing the Train_1.py

import cherrypy
import json
import os
from cherrypy import expose

class Recsys:
    @expose
    def index(self):
        return "Lets display the Reccomendations!"
    
    @expose
    def Reccomendations(self, viewer_id):
        return json.dumps(get_reccomendation(viewer_id,product_train1).to_json())

if __name__ == '__main__':
    conf = {
        '/': {
            'tools.sessions.on': True,
            'tools.staticdir.root': os.path.abspath(os.getcwd())
        },
        '/static': {
            'tools.staticdir.on': True,
            'tools.staticdir.dir': './public'
        }
    }
    cherrypy.quickstart(Recsys(), '/', conf)

